workflows:
  my-workflow:
    name: My workflow name
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        XCODE_WORKSPACE: "project.xcworkspace" # <-- Put the name of your workspace here.
        XCODE_SCHEME: "xcuserdata" # <-- Put the name of your scheme here.
        BUNDLE_ID: "io.codemagic.swiftly" # <-- Put your Bundle Id here.
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ...
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - jeremyjor299@gmail.com
      scripts:
        - echo 'Post-publish script'